# Generated by Django 4.2.29 on 2026-03-06 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_user_id', models.CharField(blank=True, max_length=255)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_storage', models.BigIntegerField(default=0)),
                ('used_storage', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('google_drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('mega', 'MEGA')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-cloud', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_types', models.JSONField(blank=True, default=list)),
                ('min_file_size', models.BigIntegerField(blank=True, null=True)),
                ('max_file_size', models.BigIntegerField(blank=True, null=True)),
                ('auto_upload', models.BooleanField(default=True)),
                ('delete_after_upload', models.BooleanField(default=False)),
                ('compress_before_upload', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_rules', to='cloud_providers.cloudconnection')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cloudconnection',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='cloud_providers.cloudprovider'),
        ),
        migrations.AddField(
            model_name='cloudconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CloudUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('provider_file_id', models.CharField(blank=True, max_length=500)),
                ('provider_file_url', models.URLField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='cloud_providers.cloudconnection')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_uploads', to='storage.file')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('file', 'connection')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cloudconnection',
            unique_together={('user', 'provider')},
        ),
    ]
